export const ADD_QUESTION_PAGE_INIT = "ADD_QUESTION_PAGE_INIT";
export const ADD_QUESTION_CHANGE_QUESTION = "ADD_QUESTION_CHANGE_QUESTION";
export const ADD_QUESTION_CHANGE_TYPE = "ADD_QUESTION_CHANGE_TYPE";
export const ADD_QUESTION_CHANGE_MCQ_OPTIONS =
  "ADD_QUESTION_CHANGE_MCQ_OPTIONS";
export const ADD_QUESTION_CHANGE_POINTS = "ADD_QUESTION_CHANGE_POINTS";
export const ADD_QUESTION_SHOW_LOADING = "ADD_QUESTION_SHOW_LOADING";
export const ADD_QUESTION_VALIDATION_ERROR = "ADD_QUESTION_VALIDATION_ERROR";
export const SET_QUESTION_DETAILS = "app/AddQuestion/SET_QUESTION_DETAILS";
