export const SET_FORUM_MESSAGES = "SET_FORUM_MESSAGES";
export const FORUM_INIT = "FORUM_INIT";
export const SET_FORUM_PAGE = "SET_FORUM_PAGE";
export const CHANGE_FORUM_INPUT = "CHANGE_FORUM_INPUT";
export const REFRESH_FORUM_MESSAGES = "REFRESH_FORUM_MESSAGES";
