export const REVIEW_PAGE_SET_LOADING = "REVIEW_PAGE_SET_LOADING";
export const REVIEW_PAGE_INIT = "REVIEW_PAGE_INIT";
export const REVIEW_PAGE_SET_DETAILS = "REVIEW_PAGE_SET_DETAILS";
export const REVIEW_PAGE_CHANGE_MARK = "REVIEW_PAGE_CHANGE_MARK";
export const REVIEW_PAGE_CHANGE_COMMENT = "REVIEW_PAGE_CHANGE_COMMENT";
export const REVIEW_PAGE_VALIDATION_ERROR = "REVIEW_PAGE_VALIDATION_ERROR";
