/*
 *
 * Dashboard constants
 *
 */

export const DEFAULT_ACTION = "app/Dashboard/DEFAULT_ACTION";
export const DASHBOARD_UPDATE_EVENTS = "DASHBOARD_UPDATE_EVENTS";
export const DASHBOARD_UPDATE_SIDEBAR_EVENTS =
  "DASHBOARD_UPDATE_SIDEBAR_EVENTS";
export const DASHBOARD_SET_LOADING = "DASHBOARD_SET_LOADING";
export const DASHBOARD_SET_PREFERENCES = "DASHBOARD_SET_PREFERENCES";
export const DOWNLOAD_PROFILE_FAILED = "DOWNLOAD_PROFILE_FAILED";
export const DOWNLOAD_PROFILE_SUCCESS = "DOWNLOAD_PROFILE_SUCCESS";
