export const CHANGE_PSWD_PAGE_INIT = "CHANGE_PSWD_PAGE_INIT";
export const CHANGE_PSWD_PAGE_CHANGE_EMAIL = "CHANGE_PSWD_PAGE_CHANGE_EMAIL";
export const CHANGE_PSWD_PAGE_CHANGE_PASSWORD =
  "CHANGE_PSWD_PAGE_CHANGE_PASSWORD";
export const CHANGE_PSWD_PAGE_CONFIRM_PASSWORD =
  "CHANGE_PSWD_PAGE_CONFIRM_PASSWORD";
export const CHANGE_PSWD_USER_SUCCESS = "CHANGE_PSWD_USER_SUCCESS";
export const CHANGE_PSWD_USER_FAILURE = "CHANGE_PSWD_USER_FAILURE";
export const CHANGE_PSWD_PAGE_SHOW_LOADING = "CHANGE_PSWD_PAGE_SHOW_LOADING";
export const CHANGE_PSWD_VALIDATION_ERROR = "CHANGE_PSWD_VALIDATION_ERROR";
