export const LOGIN_PAGE_INIT = "LOGIN_PAGE_INIT";
export const LOGIN_PAGE_CHANGE_EMAIL = "LOGIN_PAGE_CHANGE_EMAIL";
export const LOGIN_PAGE_CHANGE_PASSWORD = "LOGIN_PAGE_CHANGE_PASSWORD";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGIN_PAGE_SHOW_LOADING = "LOGIN_PAGE_SHOW_LOADING";
export const LOGIN_VALIDATION_ERROR = "LOGIN_VALIDATION_ERROR";
export const LOGIN_SET_OAUTH_CONFIG = "LOGIN_SET_OAUTH_CONFIG";
