export const RESET_PAGE_INIT = "RESET_PAGE_INIT";
export const RESET_PAGE_CHANGE_EMAIL = "RESET_PAGE_CHANGE_EMAIL";
export const RESET_PAGE_CHANGE_PASSWORD = "RESET_PAGE_CHANGE_PASSWORD";
export const RESET_USER_SUCCESS = "RESET_USER_SUCCESS";
export const RESET_USER_FAILURE = "RESET_USER_FAILURE";
export const RESET_PAGE_SHOW_LOADING = "RESET_PAGE_SHOW_LOADING";
export const RESET_VALIDATION_ERROR = "RESET_VALIDATION_ERROR";
