export const INVITE_USER_INIT = "INVITE_USER_INIT";
export const CHANGE_NAME = "CHANGE_NAME";
export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const INVITE_USER_VALIDATION_ERROR = "INVITE_USER_VALIDATION_ERROR";
export const INVITE_USER_SHOW_LOADING = "INVITE_USER_SHOW_LOADING";
