export const ADD_POLL_INIT = "ADD_POLL_INIT";
export const ADD_POLL_CHANGE_TITLE = "ADD_POLL_CHANGE_TITLE";
export const ADD_POLL_CHANGE_OPTIONS = "ADD_POLL_CHANGE_OPTIONS";
export const ADD_POLL_SHOW_LOADING = "ADD_POLL_SHOW_LOADING";
export const SET_POLL_DETAILS = "SET_POLL_DETAILS";
